const fs = require("fs"), path = require("path");

const NEW = [
  // ── SILOGISME (+9) ──
  {"id":"TIU-088","category":"TIU","sub":"Silogisme","text":"Premis 1: Semua dokter adalah lulusan kedokteran. Premis 2: Andi adalah dokter. Kesimpulan:","options":[{"id":"A","text":"Andi mungkin lulusan kedokteran","score":2},{"id":"B","text":"Andi pasti lulusan kedokteran","score":5},{"id":"C","text":"Andi bukan dokter","score":1},{"id":"D","text":"Lulusan kedokteran pasti dokter","score":4},{"id":"E","text":"Tidak bisa ditarik kesimpulan","score":3}],"correct":"B","explanation":"Silogisme kategoris: Semua dokter adalah lulusan kedokteran. Andi adalah anggota himpunan dokter. Maka Andi adalah anggota himpunan lulusan kedokteran.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-089","category":"TIU","sub":"Silogisme","text":"Semua bunga adalah tumbuhan. Sebagian tumbuhan berwarna hijau. Maka:","options":[{"id":"A","text":"Semua bunga berwarna hijau","score":1},{"id":"B","text":"Sebagian bunga berwarna hijau","score":4},{"id":"C","text":"Tidak dapat ditarik kesimpulan pasti","score":5},{"id":"D","text":"Semua tumbuhan hijau adalah bunga","score":2},{"id":"E","text":"Sebagian tumbuhan hijau bukan bunga","score":3}],"correct":"C","explanation":"Premis 1: semua bunga ⊂ tumbuhan. Premis 2: sebagian tumbuhan = hijau. Tidak ada informasi apakah bunga termasuk dalam 'sebagian' yang hijau atau tidak.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-090","category":"TIU","sub":"Silogisme","text":"Jika P maka Q. Tidak Q. Maka:","options":[{"id":"A","text":"Pasti tidak P","score":5},{"id":"B","text":"Mungkin P","score":1},{"id":"C","text":"Tidak dapat disimpulkan","score":4},{"id":"D","text":"Q terjadi","score":2},{"id":"E","text":"P dan Q keduanya benar","score":3}],"correct":"A","explanation":"Modus Tollens: (P→Q) ∧ ¬Q ∴ ¬P. Jika P mengakibatkan Q, dan Q tidak terjadi, maka P pasti tidak terjadi.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-091","category":"TIU","sub":"Silogisme","text":"Premis 1: Semua mamalia bernapas dengan paru-paru. Premis 2: Paus adalah mamalia. Premis 3: Ikan paus hidup di laut. Kesimpulan:","options":[{"id":"A","text":"Semua mamalia hidup di laut","score":1},{"id":"B","text":"Paus bernapas dengan paru-paru","score":5},{"id":"C","text":"Ikan laut bernapas dengan paru-paru","score":3},{"id":"D","text":"Semua yang hidup di laut adalah mamalia","score":2},{"id":"E","text":"Tidak dapat ditarik kesimpulan","score":4}],"correct":"B","explanation":"Dari premis 1 dan 2: Paus adalah mamalia, dan semua mamalia bernapas dengan paru-paru. Maka paus bernapas dengan paru-paru. Premis 3 (hidup di laut) tidak relevan untuk kesimpulan ini.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-092","category":"TIU","sub":"Silogisme","text":"Semua ASN wajib jujur. Sebagian pejabat adalah ASN. Maka:","options":[{"id":"A","text":"Semua pejabat wajib jujur","score":3},{"id":"B","text":"Sebagian pejabat wajib jujur","score":5},{"id":"C","text":"Semua ASN adalah pejabat","score":2},{"id":"D","text":"Tidak ada kesimpulan yang pasti","score":4},{"id":"E","text":"Semua yang jujur adalah ASN","score":1}],"correct":"D","explanation":"Premis 1: ASN ⊂ jujur. Premis 2: sebagian pejabat ⊂ ASN. Tidak ada informasi tentang pejabat yang bukan ASN, dan tidak bisa menyimpulkan 'sebagian pejabat' karena bisa saja 'semua pejabat' atau 'tidak ada pejabat' yang ASN -- tidak cukup data.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-093","category":"TIU","sub":"Silogisme","text":"Jika suatu bilangan habis dibagi 6, maka bilangan itu genap. Bilangan X tidak genap. Maka:","options":[{"id":"A","text":"X pasti habis dibagi 6","score":2},{"id":"B","text":"X tidak habis dibagi 6","score":5},{"id":"C","text":"X mungkin genap","score":1},{"id":"D","text":"X pasti ganjil","score":4},{"id":"E","text":"Tidak bisa disimpulkan","score":3}],"correct":"B","explanation":"Modus Tollens. (habis 6 → genap). Tidak genap (¬Q) maka tidak habis dibagi 6 (¬P).","xp_reward":10,"coin_reward":5},
  {"id":"TIU-094","category":"TIU","sub":"Silogisme","text":"Premis 1: Jika belajar, maka lulus. Premis 2: Budi belajar. Maka:","options":[{"id":"A","text":"Budi tidak lulus","score":1},{"id":"B","text":"Budi lulus","score":5},{"id":"C","text":"Budi mungkin lulus","score":3},{"id":"D","text":"Semua yang lulus belajar","score":4},{"id":"E","text":"Tidak bisa disimpulkan","score":2}],"correct":"B","explanation":"Modus Ponens: (P→Q) ∧ P ∴ Q. Jika belajar mengakibatkan lulus, dan Budi belajar, maka Budi lulus.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-095","category":"TIU","sub":"Silogisme","text":"Semua segitiga memiliki tiga sisi. Segiempat tidak memiliki tiga sisi. Maka:","options":[{"id":"A","text":"Segiempat adalah segitiga","score":1},{"id":"B","text":"Segiempat bukan segitiga","score":5},{"id":"C","text":"Semua bangun dengan tiga sisi adalah segitiga","score":4},{"id":"D","text":"Bisa jadi segiempat adalah segitiga","score":2},{"id":"E","text":"Tidak bisa disimpulkan","score":3}],"correct":"B","explanation":"Jika 'semua segitiga memiliki tiga sisi' = jika segitiga → tiga sisi. Bukan 'tiga sisi → segitiga'. Tapi segiempat tidak punya tiga sisi, jadi bukan segitiga. Ini modus tollens sederhana.","xp_reward":10,"coin_reward":5},

  // ── ANALOGI VERBAL (+14) ──
  {"id":"TIU-096","category":"TIU","sub":"Analogi Verbal","text":"DOKTER : PASIEN = GURU : ...","options":[{"id":"A","text":"Sekolah","score":3},{"id":"B","text":"Murid","score":5},{"id":"C","text":"Kelas","score":2},{"id":"D","text":"Pelajaran","score":4},{"id":"E","text":"Buku","score":1}],"correct":"B","explanation":"Hubungan: profesi yang melayani/mengajar. Dokter melayani pasien, guru mengajar murid.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-097","category":"TIU","sub":"Analogi Verbal","text":"PISAU : MEMOTONG = PULPEN : ...","options":[{"id":"A","text":"Menulis","score":5},{"id":"B","text":"Kertas","score":2},{"id":"C","text":"Tinta","score":4},{"id":"D","text":"Menggambar","score":3},{"id":"E","text":"Buku","score":1}],"correct":"A","explanation":"Hubungan: alat dengan fungsinya. Pisau digunakan untuk memotong, pulpen digunakan untuk menulis.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-098","category":"TIU","sub":"Analogi Verbal","text":"BURUNG : TERBANG = IKAN : ...","options":[{"id":"A","text":"Berenang","score":5},{"id":"B","text":"Air","score":3},{"id":"C","text":"Sirip","score":4},{"id":"D","text":"Laut","score":2},{"id":"E","text":"Insang","score":1}],"correct":"A","explanation":"Hubungan: hewan dengan cara bergeraknya. Burung terbang, ikan berenang.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-099","category":"TIU","sub":"Analogi Verbal","text":"BENSIN : MOBIL = LISTRIK : ...","options":[{"id":"A","text":"Kabel","score":2},{"id":"B","text":"Lampu","score":4},{"id":"C","text":"Komputer","score":1},{"id":"D","text":"Energi","score":3},{"id":"E","text":"Alat Elektronik","score":5}],"correct":"E","explanation":"Hubungan: sumber energi untuk alat. Bensin = energi untuk mobil, listrik = energi untuk alat elektronik.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-100","category":"TIU","sub":"Analogi Verbal","text":"MATAHARI : TERANG = BULAN : ...","options":[{"id":"A","text":"Gelap","score":1},{"id":"B","text":"Malam","score":5},{"id":"C","text":"Cahaya","score":4},{"id":"D","text":"Sabit","score":2},{"id":"E","text":"Terang","score":3}],"correct":"B","explanation":"Hubungan: sumber cahaya dengan waktu. Matahari terbit di siang (terang), bulan muncul di malam hari.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-101","category":"TIU","sub":"Analogi Verbal","text":"TELUR : AYAM = BIJI : ...","options":[{"id":"A","text":"Pohon","score":5},{"id":"B","text":"Buah","score":4},{"id":"C","text":"Tanah","score":2},{"id":"D","text":"Tunas","score":3},{"id":"E","text":"Bunga","score":1}],"correct":"A","explanation":"Hubungan: asal-usul. Telur dihasilkan oleh ayam, biji dihasilkan oleh pohon/tanaman.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-102","category":"TIU","sub":"Analogi Verbal","text":"KAKI : BERJALAN = MATA : ...","options":[{"id":"A","text":"Melihat","score":5},{"id":"B","text":"Wajah","score":2},{"id":"C","text":"Kacamata","score":3},{"id":"D","text":"Menatap","score":4},{"id":"E","text":"Terbuka","score":1}],"correct":"A","explanation":"Hubungan: organ dengan fungsinya. Kaki untuk berjalan, mata untuk melihat.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-103","category":"TIU","sub":"Analogi Verbal","text":"KAYU : MEJA = KAPAS : ...","options":[{"id":"A","text":"Baju","score":5},{"id":"B","text":"Pohon","score":2},{"id":"C","text":"Benang","score":4},{"id":"D","text":"Kain","score":3},{"id":"E","text":"Serat","score":1}],"correct":"A","explanation":"Hubungan: bahan baku menjadi produk. Kayu diolah menjadi meja, kapas diolah menjadi baju (pakaian).","xp_reward":10,"coin_reward":5},
  {"id":"TIU-104","category":"TIU","sub":"Analogi Verbal","text":"RUMAH : ATAP = TUBUH : ...","options":[{"id":"A","text":"Tangan","score":2},{"id":"B","text":"Kepala","score":5},{"id":"C","text":"Kaki","score":3},{"id":"D","text":"Rambut","score":1},{"id":"E","text":"Pakaian","score":4}],"correct":"B","explanation":"Hubungan: bagian paling atas. Atap berada di bagian teratas rumah, kepala berada di bagian teratas tubuh.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-105","category":"TIU","sub":"Analogi Verbal","text":"MATI : HIDUP = MALAM : ...","options":[{"id":"A","text":"Gelap","score":2},{"id":"B","text":"Pagi","score":3},{"id":"C","text":"Siang","score":5},{"id":"D","text":"Terang","score":4},{"id":"E","text":"Tidur","score":1}],"correct":"C","explanation":"Hubungan: antonim/berlawanan. Lawan dari mati adalah hidup, lawan dari malam adalah siang.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-106","category":"TIU","sub":"Analogi Verbal","text":"KENDARAAN : MOBIL = BUAH : ...","options":[{"id":"A","text":"Pisang","score":5},{"id":"B","text":"Sayur","score":1},{"id":"C","text":"Makanan","score":2},{"id":"D","text":"Apel","score":4},{"id":"E","text":"Mangga","score":3}],"correct":"A","explanation":"Hubungan: kelompok dengan anggota. Mobil adalah anggota kelompok kendaraan, pisang adalah anggota kelompok buah.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-107","category":"TIU","sub":"Analogi Verbal","text":"JAM : WAKTU = TERMOMETER : ...","options":[{"id":"A","text":"Demam","score":2},{"id":"B","text":"Celcius","score":3},{"id":"C","text":"Suhu","score":5},{"id":"D","text":"Panas","score":4},{"id":"E","text":"Dingin","score":1}],"correct":"C","explanation":"Hubungan: alat ukur dengan objek ukur. Jam mengukur waktu, termometer mengukur suhu.","xp_reward":10,"coin_reward":5},

  // ── HITUNGAN CEPAT (+8) ──
  {"id":"TIU-108","category":"TIU","sub":"Hitungan Cepat","text":"Berapa hasil 15×12 - 15×2?","options":[{"id":"A","text":"140","score":2},{"id":"B","text":"180","score":3},{"id":"C","text":"150","score":5},{"id":"D","text":"120","score":1},{"id":"E","text":"170","score":4}],"correct":"C","explanation":"15×12 = 180, 15×2 = 30. 180-30 = 150. Atau: 15×(12-2) = 15×10 = 150.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-109","category":"TIU","sub":"Hitungan Cepat","text":"Berapa hasil dari 88² - 12²?","options":[{"id":"A","text":"7.744","score":4},{"id":"B","text":"7.888","score":2},{"id":"C","text":"7.600","score":3},{"id":"D","text":"7.000","score":1},{"id":"E","text":"7.600","score":1}],"correct":"C","explanation":"Gunakan rumus a²-b² = (a+b)(a-b) = (88+12)(88-12) = 100×76 = 7.600.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-110","category":"TIU","sub":"Hitungan Cepat","text":"Berapakah 25% dari 240?","options":[{"id":"A","text":"50","score":2},{"id":"B","text":"60","score":5},{"id":"C","text":"55","score":1},{"id":"D","text":"80","score":3},{"id":"E","text":"48","score":4}],"correct":"B","explanation":"25% = 1/4. 240÷4 = 60.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-111","category":"TIU","sub":"Hitungan Cepat","text":"Berapa hasil dari 999 + 998 + 1 + 2?","options":[{"id":"A","text":"2.000","score":5},{"id":"B","text":"1.998","score":3},{"id":"C","text":"2.010","score":2},{"id":"D","text":"1.990","score":1},{"id":"E","text":"2.050","score":4}],"correct":"A","explanation":"Kelompokkan: (999+1) + (998+2) = 1000+1000 = 2000.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-112","category":"TIU","sub":"Hitungan Cepat","text":"Berapa hasil dari 50×99?","options":[{"id":"A","text":"4.850","score":3},{"id":"B","text":"4.950","score":5},{"id":"C","text":"5.000","score":4},{"id":"D","text":"4.800","score":1},{"id":"E","text":"5.050","score":2}],"correct":"B","explanation":"50×99 = 50×(100-1) = 5000-50 = 4950.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-113","category":"TIU","sub":"Hitungan Cepat","text":"Hasil dari 2⁵ × 2³ adalah...","options":[{"id":"A","text":"2⁸","score":5},{"id":"B","text":"2¹⁵","score":1},{"id":"C","text":"4⁸","score":3},{"id":"D","text":"2²","score":2},{"id":"E","text":"8⁸","score":4}],"correct":"A","explanation":"2⁵ × 2³ = 2⁵⁺³ = 2⁸.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-114","category":"TIU","sub":"Hitungan Cepat","text":"Berapakah 37,5% dari 160?","options":[{"id":"A","text":"60","score":5},{"id":"B","text":"50","score":2},{"id":"C","text":"70","score":3},{"id":"D","text":"80","score":4},{"id":"E","text":"48","score":1}],"correct":"A","explanation":"37,5% = 3/8. 160 × 3/8 = 60. Atau: 50% dari 160 = 80, 12,5% dari 160 = 20. 80-20=60.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-115","category":"TIU","sub":"Hitungan Cepat","text":"Berapa hasil dari 125 × 48?","options":[{"id":"A","text":"6.000","score":5},{"id":"B","text":"5.000","score":1},{"id":"C","text":"6.500","score":4},{"id":"D","text":"5.500","score":2},{"id":"E","text":"7.000","score":3}],"correct":"A","explanation":"125×48 = 125×8×6 = 1000×6 = 6000.","xp_reward":10,"coin_reward":5}
];

const fp = path.join(__dirname, "..", "src", "data", "questions", "tiu.json");
const d = JSON.parse(fs.readFileSync(fp, "utf-8"));
const b = d.length;
d.push(...NEW);
fs.writeFileSync(fp, JSON.stringify(d, null, 2), "utf-8");
console.log("TIU:", b, "→", d.length, "+" + NEW.length);
const s = {}; d.forEach(q => s[q.sub] = (s[q.sub]||0)+1);
Object.entries(s).sort((a,e)=>a[0].localeCompare(e[0])).forEach(([k,v]) => console.log(" ", k+":", v));
