const fs = require("fs"), path = require("path");
const NEW = [
  {"id":"TKP-081","category":"TKP","sub":"Integritas","text":"Anda menemukan bahwa data pribadi warga di database instansi bocor ke pihak tidak bertanggung jawab. Sikap Anda...","options":[{"id":"A","text":"Diam saja karena bukan tugas langsung","score":1},{"id":"B","text":"Melaporkan temuan ke atasan dan tim IT untuk segera ditangani","score":5},{"id":"C","text":"Menyimpan bukti untuk diri sendiri","score":2},{"id":"D","text":"Membicarakan dengan rekan","score":3},{"id":"E","text":"Menunggu ada yang melapor","score":4}],"correct":"B","explanation":"Integritas dalam perlindungan data adalah tanggung jawab semua pihak. Melaporkan segera ke pihak yang berwenang (atasan dan IT) adalah tindakan yang tepat, bukan diam atau menunggu.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-082","category":"TKP","sub":"Integritas","text":"Rekan Anda meminjam uang untuk biaya pengobatan keluarganya. Anda tahu ia tidak akan bisa mengembalikan dalam waktu dekat. Sikap Anda...","options":[{"id":"A","text":"Menolak dengan alasan apapun","score":1},{"id":"B","text":"Memberi pinjaman sesuai kemampuan ikhlas tanpa menagih","score":5},{"id":"C","text":"Meminjamkan dengan bunga","score":2},{"id":"D","text":"Menyuruhnya pinjam ke bank","score":3},{"id":"E","text":"Meminjamkan setengah","score":4}],"correct":"B","explanation":"Integritas juga mencakup nilai kemanusiaan. Membantu rekan yang kesulitan dengan ikhlas tanpa mengharapkan imbalan adalah tindakan mulia yang mencerminkan integritas pribadi.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-083","category":"TKP","sub":"Adaptasi","text":"Anda dipromosikan menjadi kepala unit di usia yang relatif muda. Bawahan Anda kebanyakan lebih senior. Sikap Anda...","options":[{"id":"A","text":"Bertindak otoriter agar dihormati","score":1},{"id":"B","text":"Menghormati pengalaman mereka, belajar dari yang senior, dan memimpin dengan teladan","score":5},{"id":"C","text":"Merasa tidak percaya diri","score":2},{"id":"D","text":"Mengandalkan jabatan untuk memerintah","score":3},{"id":"E","text":"Meminta nasihat atasan terus-menerus","score":4}],"correct":"B","explanation":"Adaptasi kepemimpinan: menghormati pengalaman senior sambil tetap menjalankan peran sebagai pemimpin. Belajar dari mereka dan memberi teladan adalah pendekatan terbaik.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-084","category":"TKP","sub":"Adaptasi","text":"Organisasi Anda mengalami restrukturisasi besar-besaran. Posisi dan tim Anda berubah total. Sikap Anda...","options":[{"id":"A","text":"Protes dan mengajukan pengunduran diri","score":1},{"id":"B","text":"Menerima perubahan dan beradaptasi dengan struktur baru","score":5},{"id":"C","text":"Pasrah tanpa inisiatif","score":2},{"id":"D","text":"Mencari kelemahan struktur baru","score":3},{"id":"E","text":"Menunggu kepastian","score":4}],"correct":"B","explanation":"Restrukturisasi adalah hal yang wajar dalam organisasi. Kemampuan beradaptasi dengan perubahan struktur dan menerima tantangan baru adalah kompetensi penting ASN.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-085","category":"TKP","sub":"Adaptasi","text":"Anda baru saja kembali dari tugas belajar dan diterjunkan ke unit dengan sistem kerja yang sudah berubah drastis. Sikap Anda...","options":[{"id":"A","text":"Menggunakan cara lama yang sudah dikuasai","score":1},{"id":"B","text":"Mempelajari sistem baru dari rekan dan dokumentasi dengan cepat","score":5},{"id":"C","text":"Mengeluh karena sistem terlalu rumit","score":2},{"id":"D","text":"Menunggu pelatihan formal","score":3},{"id":"E","text":"Mengerjakan yang penting dulu","score":4}],"correct":"B","explanation":"Kemampuan belajar cepat (fast learning) di lingkungan baru adalah wujud adaptasi positif. Aktif belajar dari rekan dan dokumentasi menunjukkan inisiatif.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-086","category":"TKP","sub":"Kerja Sama","text":"Tim Anda gagal mencapai target bulan ini karena koordinasi yang buruk. Sikap Anda...","options":[{"id":"A","text":"Menyalahkan anggota tim lain","score":1},{"id":"B","text":"Mengajak evaluasi bersama dan mencari solusi perbaikan ke depannya","score":5},{"id":"C","text":"Menerima kegagalan tanpa tindak lanjut","score":2},{"id":"D","text":"Meminta ganti tim","score":3},{"id":"E","text":"Melapor ke atasan bahwa tim tidak kompak","score":4}],"correct":"B","explanation":"Kerja sama berarti tanggung jawab kolektif. Evaluasi bersama dan perbaikan ke depan lebih konstruktif daripada menyalahkan atau melapor tanpa solusi.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-087","category":"TKP","sub":"Kerja Sama","text":"Anda memiliki ide bagus, tapi anggota tim lain lebih dominan dalam diskusi. Sikap Anda...","options":[{"id":"A","text":"Diam dan mengikuti pendapat dominan","score":2},{"id":"B","text":"Menyampaikan ide dengan data pendukung di momen yang tepat","score":5},{"id":"C","text":"Memaksakan ide agar didengar","score":1},{"id":"D","text":"Menitipkan ide ke anggota lain","score":3},{"id":"E","text":"Menulis di grup chat agar lebih leluasa","score":4}],"correct":"B","explanation":"Kerja sama bukan berarti mengalah terus, tetapi menyampaikan kontribusi dengan cara yang tepat waktu dan berbasis data untuk didengar dan dipertimbangkan tim.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-088","category":"TKP","sub":"Kerja Sama","text":"Rekan tim Anda terkena musibah dan tidak bisa menyelesaikan tugasnya tepat waktu. Deadline tinggal besok. Sikap Anda...","options":[{"id":"A","text":"Menyelesaikan tugas sendiri saja","score":1},{"id":"B","text":"Membantu menyelesaikan tugas rekan tersebut bersama anggota tim lain","score":5},{"id":"C","text":"Melapor ke atasan bahwa deadline tidak terpenuhi","score":3},{"id":"D","text":"Menugaskan anggota tim lain untuk mengerjakan","score":4},{"id":"E","text":"Mengabaikan karena itu tugas dia","score":2}],"correct":"B","explanation":"Kerja sama berarti saling membantu ketika salah satu anggota kesulitan. Solidaritas dan gotong royong dalam tim adalah kunci keberhasilan bersama.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-089","category":"TKP","sub":"Kerja Sama","text":"Ada perbedaan pendapat yang tajam dalam tim Anda. Suasana mulai memanas. Sikap Anda...","options":[{"id":"A","text":"Keluar dari ruangan","score":1},{"id":"B","text":"Menenangkan suasana dan mengajak diskusi berbasis data bukan emosi","score":5},{"id":"C","text":"Memihak salah satu","score":2},{"id":"D","text":"Membiarkan sampai ada yang mengalah","score":3},{"id":"E","text":"Mengalihkan topik","score":4}],"correct":"B","explanation":"Manajemen konflik tim membutuhkan kedewasaan. Menjadi mediator yang menenangkan dan mengarahkan diskusi ke data/fakta adalah kontribusi berharga untuk kerja sama.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-090","category":"TKP","sub":"Adaptasi","text":"Anda harus bekerja dengan mitra dari latar belakang budaya yang sangat berbeda. Gaya komunikasi mereka sangat langsung dan blak-blakan. Sikap Anda...","options":[{"id":"A","text":"Menyinggung perasaan dan menjauhi","score":1},{"id":"B","text":"Memahami perbedaan gaya komunikasi dan menyesuaikan cara berinteraksi","score":5},{"id":"C","text":"Membalas dengan gaya yang sama","score":3},{"id":"D","text":"Mengeluh ke atasan","score":2},{"id":"E","text":"Meminta diganti mitra lain","score":4}],"correct":"B","explanation":"Kerja sama lintas budaya membutuhkan kecerdasan budaya (cultural intelligence). Memahami dan menyesuaikan gaya komunikasi adalah bentuk adaptasi profesional.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-091","category":"TKP","sub":"Pelayanan Publik","text":"Warga mengeluh karena proses pengurusan KTP di kantor Anda lambat. Sikap Anda...","options":[{"id":"A","text":"Menjelaskan bahwa memang banyak pemohon","score":2},{"id":"B","text":"Mendengarkan keluhan, mengevaluasi alur pelayanan, dan mengusulkan perbaikan","score":5},{"id":"C","text":"Menyuruh warga bersabar","score":1},{"id":"D","text":"Mengabaikan karena sudah biasa","score":3},{"id":"E","text":"Meminta maaf tanpa tindak lanjut","score":4}],"correct":"B","explanation":"Pelayanan prima tidak hanya mendengar keluhan tetapi juga melakukan perbaikan sistem. Ini menunjukkan orientasi pelayanan yang berkelanjutan.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-092","category":"TKP","sub":"Pelayanan Publik","text":"Seorang warga difabel datang untuk mengurus dokumen. Meja pelayanan cukup tinggi dan tidak ramah kursi roda. Sikap Anda...","options":[{"id":"A","text":"Tetap melayani di meja yang ada","score":1},{"id":"B","text":"Menawarkan bantuan khusus, seperti melayani di ruang terpisah yang aksesibel","score":5},{"id":"C","text":"Menyuruh warga datang dengan pendamping","score":2},{"id":"D","text":"Meminta warga untuk berdiri","score":3},{"id":"E","text":"Menjelaskan bahwa tidak ada fasilitas khusus","score":4}],"correct":"B","explanation":"Pelayanan inklusif berarti menyesuaikan cara layanan dengan kebutuhan khusus warga. Memberikan solusi alternatif yang aksesibel adalah pelayanan prima yang berkeadilan.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-093","category":"TKP","sub":"Profesionalisme","text":"Atasan Anda sering memberikan tugas di luar jam kerja tanpa kompensasi jelas. Sikap profesional Anda...","options":[{"id":"A","text":"Menolak mentah-mentah","score":1},{"id":"B","text":"Menerima dengan profesional namun mengkomunikasikan secara sopan kebutuhan kompensasi","score":5},{"id":"C","text":"Mengerjakan asal-asalan","score":2},{"id":"D","text":"Mengeluh ke rekan","score":3},{"id":"E","text":"Mengundurkan diri","score":4}],"correct":"B","explanation":"Profesionalisme berarti tetap bekerja dengan kualitas terbaik sambil mengkomunikasikan hak secara sopan. Ini lebih konstruktif daripada konfrontasi atau pasrah.","xp_reward":10,"coin_reward":5}
];

const fp = path.join(__dirname, "..", "src", "data", "questions", "tkp.json");
const d = JSON.parse(fs.readFileSync(fp, "utf-8"));
const b = d.length; d.push(...NEW);
fs.writeFileSync(fp, JSON.stringify(d, null, 2), "utf-8");
console.log("TKP:", b, "→", d.length, "+" + NEW.length);
const s = {}; d.forEach(q => s[q.sub] = (s[q.sub]||0)+1);
Object.entries(s).sort((a,e)=>a[0].localeCompare(e[0])).forEach(([k,v]) => console.log(" ", k+":", v));
