/**
 * Batch TWK: remaining subs (Bahasa Indonesia, Nasionalisme, Bela Negara, Integritas, Pilar Negara)
 */
const fs = require('fs');
const path = require('path');

const NEW = [
  // ── BAHASA INDONESIA (+5) ──
  {"id":"TWK-076","category":"TWK","sub":"Bahasa Indonesia","text":"Penggunaan kata baku yang tepat dalam kalimat berikut ini adalah...","options":[{"id":"A","text":"Pegawai tersebut sedang mengadakan analisa terhadap data keuangan","score":2},{"id":"B","text":"Pegawai tersebut sedang mengadakan analisis terhadap data keuangan","score":5},{"id":"C","text":"Pegawai tersebut sedang mengadakan analisa pada data keuangan","score":1},{"id":"D","text":"Pegawai tersebut melakukan analis terhadap data keuangan","score":3},{"id":"E","text":"Pegawai tersebut telah menganalisa data keuangan","score":4}],"correct":"B","explanation":"Kata baku yang tepat adalah 'analisis' (bukan 'analisa'). Bentuk kata kerja bakunya adalah 'menganalisis' (bukan 'menganalisa'). KBBI mencatat 'analisis' sebagai bentuk baku untuk padanan kata 'analysis'.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-077","category":"TWK","sub":"Bahasa Indonesia","text":"Kalimat yang menggunakan ejaan yang benar sesuai PUEBI adalah...","options":[{"id":"A","text":"Dia bekerja di Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi","score":5},{"id":"B","text":"Dia bekerja di kementerian pendidikan, kebudayaan, riset dan teknologi","score":3},{"id":"C","text":"Dia bekerja di kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi","score":4},{"id":"D","text":"Dia bekerja di Kementerian Pendidikan Kebudayaan Riset dan Teknologi","score":2},{"id":"E","text":"Dia bekerja di Kementerian pendidikan kebudayaan riset dan teknologi","score":1}],"correct":"A","explanation":"Nama lembaga resmi ditulis dengan huruf kapital di setiap awal kata, termasuk kata tugas 'dan' jika menjadi bagian nama resmi. PUEBI menyebutkan bahwa nama resmi lembaga negara ditulis dengan huruf kapital dan koma digunakan untuk memisahkan unsur dalam perincian.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-078","category":"TWK","sub":"Bahasa Indonesia","text":"Penulisan kata depan 'di' yang benar terdapat pada kalimat...","options":[{"id":"A","text":"Surat itu ditandatangani diruang direktur utama","score":2},{"id":"B","text":"Dimana saja lokasi pelatihan ASN akan diselenggarakan?","score":1},{"id":"C","text":"Berkas disimpan di dalam lemari arsip kantor","score":5},{"id":"D","text":"Disini semua pegawai wajib mentaati aturan","score":3},{"id":"E","text":"Beliau dilahirkan disebuah desa di Jawa Tengah","score":4}],"correct":"C","explanation":"Kata depan 'di' (penanda tempat) ditulis terpisah: 'di dalam', 'di kantor', 'di sini'. 'di' yang merupakan awalan ditulis serangkai: 'ditandatangani', 'disimpan', 'dilahirkan'. Bedanya: jika 'di' bisa diganti 'ke'/'dari', berarti kata depan (pisah).","xp_reward":10,"coin_reward":5},
  {"id":"TWK-079","category":"TWK","sub":"Bahasa Indonesia","text":"Penulisan singkatan gelar yang sesuai dengan PUEBI adalah...","options":[{"id":"A","text":"Dr. Andi Pratama S.H., M.H.","score":2},{"id":"B","text":"Andi Pratama, S.H.,M.H.","score":4},{"id":"C","text":"Andi Pratama, S.H., M.H.","score":5},{"id":"D","text":"dr. Andi Pratama, SH, MH","score":1},{"id":"E","text":"Andi Pratama, S.H, M.H","score":3}],"correct":"C","explanation":"Penulisan gelar: singkatan gelar diikuti titik, dipisahkan koma dari nama, antar gelar dipisah koma dan spasi. 'S.H.' (Sarjana Hukum), 'M.H.' (Magister Hukum). Kata 'dr.' (dokter) ditulis nonkapital dan diletakkan di depan nama tanpa koma.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-080","category":"TWK","sub":"Bahasa Indonesia","text":"Penggunaan tanda koma yang tepat terdapat pada kalimat...","options":[{"id":"A","text":"Karena sakit kepala dia tidak masuk kantor hari ini","score":2},{"id":"B","text":"Setelah menyelesaikan laporan keuangan, bulan lalu, tim audit mulai memeriksa data","score":3},{"id":"C","text":"Presiden, menteri, dan pejabat tinggi negara hadir di acara tersebut","score":5},{"id":"D","text":"Tugasnya meliputi: membalas surat, mengarsipkan dokumen dan, menyusun laporan","score":1},{"id":"E","text":"Dia berkata bahwa, semua pegawai harus hadir tepat waktu","score":4}],"correct":"C","explanation":"PUEBI: tanda koma digunakan dalam perincian lebih dari dua unsur. Kalimat A kurang koma setelah 'kepala', B kelebihan koma setelah 'bulan lalu', D kelebihan koma setelah 'dan', E tanda koma setelah 'bahwa' tidak diperlukan.","xp_reward":10,"coin_reward":5},

  // ── NASIONALISME (+5) ──
  {"id":"TWK-081","category":"TWK","sub":"Nasionalisme","text":"Seorang ASN bertugas di perbatasan Indonesia-Malaysia. Masyarakat di sana lebih sering menggunakan mata uang ringgit dan menonton siaran televisi Malaysia. Sikap nasionalisme yang paling tepat ditunjukkan ASN tersebut adalah...","options":[{"id":"A","text":"Melarang warga menggunakan mata uang asing dengan sanksi tegas","score":2},{"id":"B","text":"Membiarkan karena tidak ada aturan yang melarang secara spesifik","score":1},{"id":"C","text":"Mengedukasi masyarakat tentang pentingnya mencintai produk dalam negeri dan tetap menggunakan rupiah","score":5},{"id":"D","text":"Melaporkan warga ke pihak kepolisian karena dianggap tidak nasionalis","score":3},{"id":"E","text":"Meminta bantuan TNI untuk menertibkan penggunaan mata uang asing","score":4}],"correct":"C","explanation":"Nasionalisme bukan tentang pemaksaan atau pelarangan, melainkan tentang edukasi dan penguatan identitas bangsa. ASN seharusnya memberikan pemahaman tentang pentingnya cinta tanah air, penggunaan mata uang rupiah, dan produk dalam negeri secara persuasif.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-082","category":"TWK","sub":"Nasionalisme","text":"Dalam era globalisasi, batas-batas negara semakin kabur akibat kemajuan teknologi informasi. Sikap nasionalisme yang tepat bagi generasi muda Indonesia adalah...","options":[{"id":"A","text":"Menolak semua pengaruh budaya asing dan hanya menggunakan produk lokal","score":2},{"id":"B","text":"Terbuka terhadap budaya global tetapi tetap menjunjung tinggi budaya dan identitas bangsa","score":5},{"id":"C","text":"Mengabaikan budaya Indonesia karena dianggap ketinggalan zaman","score":1},{"id":"D","text":"Mengadopsi budaya asing sepenuhnya untuk tidak ketinggalan","score":3},{"id":"E","text":"Mengkritik semua bentuk modernisasi karena merusak budaya bangsa","score":4}],"correct":"B","explanation":"Nasionalisme di era globalisasi adalah sikap selektif: terbuka terhadap kemajuan global namun tetap mempertahankan identitas dan jati diri bangsa (cultural filter). Sikap ini dikenal sebagai 'nasionalisme kosmopolitan' atau 'nasionalisme terbuka'.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-083","category":"TWK","sub":"Nasionalisme","text":"Seorang pejabat publik mengetahui bahwa ada kebijakan asing yang dapat merugikan kepentingan nasional. Tindakan paling nasionalis yang dilakukan pejabat tersebut adalah...","options":[{"id":"A","text":"Mengabaikan karena bukan kewenangan langsungnya","score":1},{"id":"B","text":"Menyampaikan keberatan melalui saluran diplomatik resmi","score":5},{"id":"C","text":"Membocorkan informasi ke media massa","score":3},{"id":"D","text":"Mengundang investor asing untuk bernegosiasi ulang","score":4},{"id":"E","text":"Melakukan demonstrasi di depan kedutaan asing","score":2}],"correct":"B","explanation":"Nasionalisme dalam konteks kenegaraan diwujudkan melalui jalur resmi dan prosedural. Menyampaikan keberatan melalui saluran diplomatik adalah tindakan yang tepat karena menghormati hierarki dan protokol kenegaraan, serta menjaga hubungan bilateral yang profesional.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-084","category":"TWK","sub":"Nasionalisme","text":"Indonesia mengimpor beras dari negara lain saat produksi dalam negeri menurun akibat cuaca ekstrem. Tindakan yang paling mencerminkan nasionalisme dalam situasi ini adalah...","options":[{"id":"A","text":"Menolak impor beras dan membiarkan harga naik","score":1},{"id":"B","text":"Mendukung impor sambil meningkatkan produksi beras nasional secara bertahap","score":5},{"id":"C","text":"Mengganti konsumsi beras dengan makanan impor","score":2},{"id":"D","text":"Membeli beras impor lebih banyak untuk cadangan","score":3},{"id":"E","text":"Mengalihkan anggaran pertanian ke sektor lain","score":4}],"correct":"B","explanation":"Nasionalisme ekonomi bukan berarti anti-impor, melakukan kebijakan yang rasional dan berorientasi pada kemandirian jangka panjang. Impor bersifat taktis untuk stabilitas, sementara peningkatan produksi dalam negeri adalah strategis.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-085","category":"TWK","sub":"Nasionalisme","text":"Seorang siswa Indonesia mendapat beasiswa kuliah di luar negeri. Setelah lulus, ia ditawari pekerjaan dengan gaji tinggi di perusahaan multinasional di sana. Sikap yang paling mencerminkan nasionalisme adalah...","options":[{"id":"A","text":"Menerima tawaran tersebut karena lebih menguntungkan secara finansial","score":3},{"id":"B","text":"Pulang ke Indonesia untuk mengabdikan ilmu bagi kemajuan bangsa","score":5},{"id":"C","text":"Tetap di luar negeri tetapi mengirimkan sebagian gaji ke Indonesia","score":4},{"id":"D","text":"Menolak tawaran perusahaan asing karena alasan ideologis","score":2},{"id":"E","text":"Tetap di luar negeri untuk mengembangkan jejaring internasional","score":1}],"correct":"B","explanation":"Nasionalisme diwujudkan dengan pengabdian nyata kepada bangsa dan negara. Meskipun bekerja di luar negeri bukan tindakan tidak nasionalis, opsi pulang dan mengabdikan ilmu untuk kemajuan bangsa merupakan bentuk nasionalisme yang paling tinggi.","xp_reward":10,"coin_reward":5},

  // ── BELA NEGARA (+5) ──
  {"id":"TWK-086","category":"TWK","sub":"Bela Negara","text":"UU No. 3 Tahun 2002 tentang Pertahanan Negara menyebutkan bahwa setiap warga negara berhak dan wajib ikut serta dalam upaya bela negara. Bentuk partisipasi bela negara bagi seorang guru ASN yang paling tepat adalah...","options":[{"id":"A","text":"Ikut latihan militer setiap akhir pekan","score":3},{"id":"B","text":"Menanamkan nilai-nilai Pancasila dan cinta tanah air kepada siswa","score":5},{"id":"C","text":"Mendaftar sebagai anggota cadangan TNI","score":4},{"id":"D","text":"Menyumbangkan sebagian gaji untuk dana pertahanan","score":2},{"id":"E","text":"Berpatroli di lingkungan sekolah setiap malam","score":1}],"correct":"B","explanation":"Bela negara tidak selalu berarti militer. Bagi seorang guru, bentuk bela negara yang paling tepat adalah menanamkan nilai-nilai kebangsaan, cinta tanah air, dan kesadaran berbangsa kepada generasi muda melalui pendidikan. Ini termasuk dalam kategori bela negara secara psikis dan edukatif.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-087","category":"TWK","sub":"Bela Negara","text":"Ancaman terhadap negara tidak hanya datang dari militer asing, tetapi juga dari dalam negeri seperti narkoba, radikalisme, dan korupsi. Bentuk bela negara untuk melawan ancaman narkoba yang paling efektif adalah...","options":[{"id":"A","text":"Menjadi informan polisi untuk melaporkan pengedar narkoba","score":3},{"id":"B","text":"Tidak menggunakan narkoba dan mengedukasi lingkungan sekitar tentang bahayanya","score":5},{"id":"C","text":"Membentuk kelompok main hakim sendiri untuk menangkap pengedar","score":1},{"id":"D","text":"Menghindari pergaulan sama sekali","score":2},{"id":"E","text":"Mendukung program hukuman mati bagi pengedar narkoba","score":4}],"correct":"B","explanation":"Bela negara melawan narkoba dimulai dari diri sendiri (tidak menggunakan) dan berlanjut ke lingkungan sekitar (edukasi). Ini sejalan dengan konsep pertahanan negara nonmiliter yang menekankan pada kesadaran dan partisipasi aktif warga negara.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-088","category":"TWK","sub":"Bela Negara","text":"Indonesia menghadapi ancaman siber yang semakin meningkat. Sebagai ASN yang bekerja di bidang teknologi informasi, upaya bela negara yang paling tepat adalah...","options":[{"id":"A","text":"Melakukan serangan balik ke server peretas","score":2},{"id":"B","text":"Meningkatkan keamanan sistem informasi instansi dan melaporkan potensi ancaman siber","score":5},{"id":"C","text":"Membagikan data penting ke publik agar transparan","score":1},{"id":"D","text":"Mengabaikan ancaman karena bukan bidang tugas utama","score":3},{"id":"E","text":"Memasang antivirus gratis dari internet","score":4}],"correct":"B","explanation":"Ancaman siber termasuk dalam ancaman nonmiliter yang diakui dalam sistem pertahanan negara. ASN di bidang TI berkontribusi dengan mengamankan sistem informasi instansi pemerintah dan melaporkan potensi ancaman ke pihak berwenang seperti BSSN.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-089","category":"TWK","sub":"Bela Negara","text":"Seorang warga negara Indonesia yang tinggal di daerah perbatasan melihat adanya aktivitas penambangan ilegal oleh pihak asing di wilayah NKRI. Tindakan yang paling sesuai dengan semangat bela negara adalah...","options":[{"id":"A","text":"Mendokumentasikan dan melaporkan ke aparat keamanan setempat","score":5},{"id":"B","text":"Menghadapi langsung para penambang ilegal","score":2},{"id":"C","text":"Diam saja karena takut","score":1},{"id":"D","text":"Membagikan informasi di media sosial","score":3},{"id":"E","text":"Meminta ganti rugi kepada penambang ilegal","score":4}],"correct":"A","explanation":"Bela negara dapat dilakukan dengan menjadi warga negara yang baik (good citizenship): melaporkan pelanggaran kedaulatan negara melalui prosedur resmi kepada aparat keamanan. Dokumentasi diperlukan sebagai bukti untuk tindakan hukum preventif.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-090","category":"TWK","sub":"Bela Negara","text":"Salah satu wujud bela negara secara psikis adalah memiliki kesadaran berbangsa dan bernegara. Indikator kesadaran berbangsa yang paling fundamental adalah...","options":[{"id":"A","text":"Menghafal lagu kebangsaan dan lambang negara","score":3},{"id":"B","text":"Memiliki rasa memiliki terhadap bangsa dan bangga menjadi bagian dari Indonesia","score":5},{"id":"C","text":"Mengoleksi atribut bendera dan lambang negara","score":2},{"id":"D","text":"Menggunakan pakaian adat setiap hari Jumat","score":1},{"id":"E","text":"Mengikuti upacara bendera setiap Senin","score":4}],"correct":"B","explanation":"Bela negara secara psikis bukan soal ritual atau atribut, melainkan kesadaran internal tentang identitas kebangsaan. Rasa memiliki (sense of belonging) dan kebanggaan menjadi bagian dari bangsa Indonesia adalah fondasi bela negara yang paling mendasar.","xp_reward":10,"coin_reward":5},

  // ── INTEGRITAS (+5) ──
  {"id":"TWK-091","category":"TWK","sub":"Integritas","text":"Seorang ASN mendapati bahwa rekan kerjanya memalsukan tanda tangan atasan untuk menyetujui pencairan dana. Mengetahui hal ini, langkah yang paling berintegritas adalah...","options":[{"id":"A","text":"Ikut menandatangani agar rekan tidak dipermalukan","score":1},{"id":"B","text":"Menegur rekan secara pribadi dan mendorongnya untuk melaporkan diri","score":5},{"id":"C","text":"Melaporkan langsung ke Kepolisian tanpa bicara dengan rekan","score":4},{"id":"D","text":"Mengabaikan karena bukan urusan pribadi","score":2},{"id":"E","text":"Membicarakan dengan pegawai lain di kantin","score":3}],"correct":"B","explanation":"Integritas berarti konsisten antara nilai dan tindakan. Pendekatan terbaik adalah menegur secara pribadi terlebih dahulu (memberi kesempatan memperbaiki), lalu mendorong pelaporan diri. Ini menyeimbangkan nilai kejujuran dengan nilai kemanusiaan.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-092","category":"TWK","sub":"Integritas","text":"Atasan Anda meminta untuk memproses pencairan anggaran tanpa dokumen pendukung yang lengkap karena 'sudah ada perjanjian lisan'. Tindakan ASN yang berintegritas adalah...","options":[{"id":"A","text":"Memproses karena sudah diperintahkan atasan","score":2},{"id":"B","text":"Menolak dengan sopan dan menjelaskan bahwa prosedur harus dipenuhi","score":5},{"id":"C","text":"Memproses setengahnya saja","score":1},{"id":"D","text":"Mencari dokumen sendiri agar terlihat rajin","score":3},{"id":"E","text":"Melaporkan atasan ke KPK tanpa klarifikasi","score":4}],"correct":"B","explanation":"Integritas mengharuskan ASN taat pada prosedur, bukan hanya pada atasan. Menolak dengan sopan dan menjelaskan dasar hukumnya adalah bentuk keberanian moral (moral courage). ASN wajib menerapkan prinsip akuntabilitas dalam pengelolaan keuangan negara.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-093","category":"TWK","sub":"Integritas","text":"Seorang ASN ditawari hadiah oleh pengusaha yang baru saja memenangkan tender proyek di instansinya. Hadiah tersebut diberikan sebagai 'ucapan terima kasih'. Sikap yang berintegritas adalah...","options":[{"id":"A","text":"Menerima karena tidak ada hubungannya dengan keputusan tender","score":1},{"id":"B","text":"Menolak dengan tegas dan melaporkan ke unit pengawas internal","score":5},{"id":"C","text":"Menerima tetapi melaporkan ke KPK","score":4},{"id":"D","text":"Menolak tetapi tidak melaporkan","score":3},{"id":"E","text":"Menerima dan membagikan ke rekan sekantor","score":2}],"correct":"B","explanation":"Penerimaan gratifikasi oleh ASN dilarang meskipun tidak terkait langsung dengan keputusan. UU No. 20/2001 tentang Pemberantasan Tipikor mengatur bahwa ASN wajib menolak gratifikasi dan melaporkannya ke KPK atau unit pengawas internal dalam waktu 30 hari.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-094","category":"TWK","sub":"Integritas","text":"Anda menemukan bahwa laporan kinerja bulanan yang Anda susun telah diubah oleh atasan tanpa sepengetahuan Anda, dengan menambahkan data yang tidak valid. Sikap yang mencerminkan integritas adalah...","options":[{"id":"A","text":"Diam saja karena atasan yang bertanggung jawab","score":2},{"id":"B","text":"Mengklarifikasi ke atasan dan meminta koreksi data yang tidak valid","score":5},{"id":"C","text":"Mengubah kembali laporan tanpa memberitahu atasan","score":1},{"id":"D","text":"Membuat laporan versi sendiri dan menyebarkannya","score":3},{"id":"E","text":"Mengundurkan diri karena merasa tidak dihargai","score":4}],"correct":"B","explanation":"Integritas mengharuskan ASN bertanggung jawab atas data dan informasi yang dikeluarkan. Mengklarifikasi dengan atasan secara profesional adalah langkah yang tepat sebelum mengambil tindakan lebih lanjut.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-095","category":"TWK","sub":"Integritas","text":"Seorang ASN mengetahui bahwa instansinya akan melakukan audit mendadak. Rekan kerjanya mengusulkan untuk 'merapikan' beberapa dokumen agar terlihat baik. Sikap yang berintegritas adalah...","options":[{"id":"A","text":"Ikut merapikan karena demi nama baik instansi","score":2},{"id":"B","text":"Menolak dan memastikan dokumen disajikan apa adanya sesuai fakta","score":5},{"id":"C","text":"Diam saja dan membiarkan rekan mengerjakannya","score":1},{"id":"D","text":"Melaporkan rekan ke atasan","score":3},{"id":"E","text":"Merapikan yang memang perlu, membiarkan yang tidak","score":4}],"correct":"B","explanation":"Integritas berarti menyajikan informasi apa adanya tanpa manipulasi. Audit bertujuan untuk perbaikan, bukan untuk mencari-cari kesalahan. Manipulasi dokumen justru merugikan instansi dalam jangka panjang.","xp_reward":10,"coin_reward":5},

  // ── PILAR NEGARA (+5) ──
  {"id":"TWK-096","category":"TWK","sub":"Pilar Negara","text":"Empat pilar kehidupan berbangsa dan bernegara Indonesia terdiri dari...","options":[{"id":"A","text":"Pancasila, UUD 1945, NKRI, dan Bhinneka Tunggal Ika","score":5},{"id":"B","text":"Pancasila, UUD 1945, Trias Politika, dan Demokrasi","score":3},{"id":"C","text":"Pancasila, Proklamasi, NKRI, dan Bahasa Indonesia","score":2},{"id":"D","text":"UUD 1945, GBHN, Tap MPR, dan Perpu","score":1},{"id":"E","text":"Pancasila, UUD 1945, Tap MPR, dan Demokrasi","score":4}],"correct":"A","explanation":"Empat pilar kebangsaan Indonesia adalah: (1) Pancasila sebagai dasar negara dan ideologi, (2) UUD 1945 sebagai konstitusi, (3) NKRI sebagai bentuk negara, dan (4) Bhinneka Tunggal Ika sebagai semboyan pemersatu. Keempatnya merupakan konsensus dasar berbangsa dan bernegara.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-097","category":"TWK","sub":"Pilar Negara","text":"Implementasi Pancasila sebagai pilar pertama dalam kehidupan sehari-hari ASN adalah...","options":[{"id":"A","text":"Menghafal sila-sila Pancasila di luar kepala","score":1},{"id":"B","text":"Menjadikan Pancasila sebagai pedoman dalam setiap pengambilan keputusan dan pelayanan publik","score":5},{"id":"C","text":"Memasang lambang Pancasila di ruang kerja","score":3},{"id":"D","text":"Menyebutkan Pancasila dalam setiap pidato","score":2},{"id":"E","text":"Menulis makalah tentang Pancasila","score":4}],"correct":"B","explanation":"Pancasila sebagai pilar negara bukan sekadar simbol atau hafalan, melainkan harus diimplementasikan dalam tindakan nyata. Bagi ASN, Pancasila harus menjadi dasar dalam pelayanan publik dan pengambilan keputusan, seperti keadilan sosial dan musyawarah mufakat.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-098","category":"TWK","sub":"Pilar Negara","text":"NKRI sebagai pilar ketiga memiliki makna bahwa bentuk negara Indonesia adalah kesatuan. Konsekuensi dari bentuk negara kesatuan adalah...","options":[{"id":"A","text":"Setiap provinsi memiliki undang-undang dasar sendiri","score":1},{"id":"B","text":"Kedaulatan negara berada di tangan pemerintah pusat dan daerah secara berimbang","score":2},{"id":"C","text":"Pemerintah pusat memegang kedaulatan penuh, namun daerah diberikan otonomi seluas-luasnya","score":5},{"id":"D","text":"Daerah dapat memisahkan diri dari NKRI melalui referendum","score":3},{"id":"E","text":"Pemerintah daerah memiliki kedaulatan penuh atas wilayahnya","score":4}],"correct":"C","explanation":"NKRI sebagai negara kesatuan berarti kedaulatan berada di tangan pemerintah pusat, tetapi daerah diberikan otonomi seluas-luasnya dalam kerangka NKRI (desentralisasi). Tidak ada negara bagian, dan daerah tidak dapat memisahkan diri.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-099","category":"TWK","sub":"Pilar Negara","text":"Bhinneka Tunggal Ika sebagai pilar keempat memiliki makna yang paling tepat dalam konteks ASN adalah...","options":[{"id":"A","text":"Semua suku dan budaya harus diseragamkan","score":1},{"id":"B","text":"Perbedaan adalah kekayaan yang harus dihargai dan dikelola dalam bingkai persatuan","score":5},{"id":"C","text":"Keberagaman hanya untuk simbol nasional","score":2},{"id":"D","text":"Perbedaan dapat diabaikan demi persatuan","score":3},{"id":"E","text":"Keberagaman harus dikurangi agar mudah dikelola","score":4}],"correct":"B","explanation":"Bhinneka Tunggal Ika bermakna 'berbeda-beda tetapi tetap satu'. Dalam pelayanan publik, ASN harus menghargai dan melayani semua warga tanpa diskriminasi suku, agama, ras, atau golongan, karena semua warga negara memiliki hak yang sama.","xp_reward":10,"coin_reward":5},
  {"id":"TWK-100","category":"TWK","sub":"Pilar Negara","text":"UUD 1945 sebagai pilar kedua berfungsi sebagai konstitusi negara. Kedudukan UUD 1945 dalam hierarki peraturan perundang-undangan adalah...","options":[{"id":"A","text":"Setara dengan undang-undang","score":2},{"id":"B","text":"Tertinggi setelah Pancasila","score":5},{"id":"C","text":"Di bawah Peraturan Pemerintah Pengganti Undang-Undang","score":1},{"id":"D","text":"Setara dengan Ketetapan MPR","score":3},{"id":"E","text":"Di bawah Pancasila dan di atas UU","score":4}],"correct":"B","explanation":"Dalam hierarki peraturan perundang-undangan Indonesia (Pasal 7 UU No. 12/2011), UUD 1945 menempati urutan tertinggi setelah Pancasila sebagai sumber dari segala sumber hukum. Semua peraturan di bawahnya tidak boleh bertentangan dengan UUD 1945.","xp_reward":10,"coin_reward":5}
];

const filePath = path.join(__dirname, '..', 'src', 'data', 'questions', 'twk.json');
const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
const before = data.length;
data.push(...NEW);
fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
console.log(`TWK batch 2: ${before} → ${data.length} (${NEW.length} baru)`);

// Per sub
const subs = {};
data.forEach(q => subs[q.sub] = (subs[q.sub]||0)+1);
Object.entries(subs).sort((a,b)=>a[0].localeCompare(b[0])).forEach(([k,v])=>console.log(`  ${k}: ${v}`));
