const fs = require("fs"), path = require("path");
const NEW = [
  // ── INTEGRITAS (+12 lebih) ──
  {"id":"TKP-067","category":"TKP","sub":"Integritas","text":"Anda menemukan rekan kerja yang mengambil ATK (alat tulis kantor) untuk kepentingan pribadi secara rutin. Sikap Anda...","options":[{"id":"A","text":"Ikut mengambil karena banyak yang melakukannya","score":1},{"id":"B","text":"Menegur rekan dan mengingatkan bahwa ATK adalah aset negara","score":5},{"id":"C","text":"Melaporkan ke atasan langsung","score":4},{"id":"D","text":"Diam saja","score":2},{"id":"E","text":"Mengambil juga tapi diam-diam","score":3}],"correct":"B","explanation":"Integritas diuji dalam hal kecil sekalipun. ATK kantor adalah aset negara yang penggunaannya harus untuk kepentingan dinas. Menegur dengan baik lebih efektif daripada langsung melapor.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-068","category":"TKP","sub":"Integritas","text":"Anda mendapat kelebihan uang belanja dinas. Tidak ada yang tahu. Sikap Anda...","options":[{"id":"A","text":"Menyimpan karena sudah jerih payah","score":1},{"id":"B","text":"Mengembalikan ke kas negara dengan prosedur yang benar","score":5},{"id":"C","text":"Menyimpan setengah, mengembalikan setengah","score":2},{"id":"D","text":"Menanyakan ke rekan yang lebih senior","score":3},{"id":"E","text":"Menyumbangkan ke tempat ibadah","score":4}],"correct":"B","explanation":"Integritas keuangan negara bersifat mutlak. Kelebihan anggaran harus dikembalikan, sekecil apapun jumlahnya. Ini sesuai prinsip akuntabilitas ASN.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-069","category":"TKP","sub":"Integritas","text":"Atasan meminta Anda memanipulasi data laporan agar terlihat lebih baik di hadapan pimpinan. Sikap Anda...","options":[{"id":"A","text":"Mematuhi perintah atasan","score":1},{"id":"B","text":"Menolak dengan sopan dan menjelaskan konsekuensi hukum dari manipulasi data","score":5},{"id":"C","text":"Memanipulasi sedikit saja","score":2},{"id":"D","text":"Mengalihkan tugas ke pegawai lain","score":3},{"id":"E","text":"Melaporkan ke inspektorat tanpa klarifikasi","score":4}],"correct":"B","explanation":"Integritas lebih penting daripada loyalitas buta. Menolak dengan sopan sambil menjelaskan risiko hukum adalah tindakan yang paling berintegritas. ASN wajib melaporkan data sesuai fakta.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-070","category":"TKP","sub":"Integritas","text":"Anda diminta menandatangani dokumen yang tidak sesuai dengan kondisi lapangan. Sikap Anda...","options":[{"id":"A","text":"Menandatangani karena sudah diperintahkan","score":1},{"id":"B","text":"Menolak menandatangani dan meminta perbaikan data","score":5},{"id":"C","text":"Menandatangani dengan catatan","score":3},{"id":"D","text":"Menitipkan tanda tangan ke rekan","score":2},{"id":"E","text":"Mengusulkan perubahan lewat memo","score":4}],"correct":"B","explanation":"Tanda tangan adalah bentuk pertanggungjawaban pribadi. Menandatangani dokumen palsu berarti ikut serta dalam pemalsuan. Menolak dan meminta perbaikan adalah sikap integritas.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-071","category":"TKP","sub":"Integritas","text":"Anda tidak sengaja merusak printer kantor. Tidak ada saksi. Sikap Anda...","options":[{"id":"A","text":"Diam saja berharap tidak ketahuan","score":1},{"id":"B","text":"Melapor ke bagian perlengkapan dan bertanggung jawab","score":5},{"id":"C","text":"Memperbaiki sendiri diam-diam","score":3},{"id":"D","text":"Menyalahkan rekan","score":2},{"id":"E","text":"Mengaku tapi menawar tanggung jawab","score":4}],"correct":"B","explanation":"Integritas berarti mengakui kesalahan meskipun tidak ada saksi. Melapor dan bertanggung jawab adalah sikap dewasa dan profesional yang membangun kepercayaan.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-072","category":"TKP","sub":"Integritas","text":"Seorang pengusaha menawarkan 'fee' agar Anda mempercepat proses izin usahanya. Sikap Anda...","options":[{"id":"A","text":"Menerima karena itu hak pengusaha untuk berterima kasih","score":1},{"id":"B","text":"Menolak dan memproses sesuai prosedur yang berlaku","score":5},{"id":"C","text":"Menerima dengan syarat proses sesuai aturan","score":2},{"id":"D","text":"Menolak tapi memperlambat proses","score":3},{"id":"E","text":"Menanyakan ke atasan terlebih dahulu","score":4}],"correct":"B","explanation":"Penerimaan gratifikasi dalam bentuk apapun terkait proses perizinan adalah pelanggaran. ASN wajib menolak dan tetap memproses sesuai prosedur tanpa diskriminasi.","xp_reward":10,"coin_reward":5},

  // ── ADAPTASI (+11) ──
  {"id":"TKP-073","category":"TKP","sub":"Adaptasi","text":"Kebijakan baru mengharuskan work from office (WFO) 5 hari setelah sebelumnya fleksibel. Sikap Anda...","options":[{"id":"A","text":"Mengajukan keberatan resmi","score":2},{"id":"B","text":"Menerima dan menyesuaikan jadwal pribadi","score":5},{"id":"C","text":"Tetap work from home diam-diam","score":1},{"id":"D","text":"Mencari pekerjaan lain","score":3},{"id":"E","text":"Membicarakan dengan kolega","score":4}],"correct":"B","explanation":"Perubahan kebijakan adalah hal biasa dalam organisasi. Kemampuan adaptasi ditunjukkan dengan menerima dan menyesuaikan diri, bukan melawan perubahan.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-074","category":"TKP","sub":"Adaptasi","text":"Anda dipindahkan ke kota baru yang budaya dan bahasanya sangat berbeda. Sikap Anda...","options":[{"id":"A","text":"Tetap menggunakan bahasa daerah sendiri","score":1},{"id":"B","text":"Belajar bahasa dan budaya setempat untuk beradaptasi","score":5},{"id":"C","text":"Minta pindah kembali","score":2},{"id":"D","text":"Bergaul hanya dengan sesama pendatang","score":3},{"id":"E","text":"Mengeluh ke atasan","score":4}],"correct":"B","explanation":"Adaptasi lintas budaya adalah kemampuan penting ASN di era desentralisasi. Mempelajari bahasa dan budaya setempat memudahkan pelayanan publik dan integrasi sosial.","xp_reward":10,"coin_reward":5},
  
  // ── KERJA SAMA (+12) ──
  {"id":"TKP-075","category":"TKP","sub":"Kerja Sama","text":"Tim Anda mendapat proyek dengan deadline sangat ketat. Masing-masing anggota sudah sibuk dengan tugas sendiri. Sikap Anda...","options":[{"id":"A","text":"Mengerjakan tugas sendiri saja","score":1},{"id":"B","text":"Mengusulkan pembagian kerja yang jelas dan saling membantu jika ada yang kewalahan","score":5},{"id":"C","text":"Minta tambahan anggota tim","score":3},{"id":"D","text":"Mengerjakan semuanya sendiri","score":2},{"id":"E","text":"Lembur sendiri tanpa koordinasi","score":4}],"correct":"B","explanation":"Kerja sama efektif membutuhkan koordinasi dan pembagian kerja yang jelas, serta kesediaan membantu rekan yang kesulitan.","xp_reward":10,"coin_reward":5},
  
  // ── PELAYANAN PUBLIK (+8) ──
  {"id":"TKP-076","category":"TKP","sub":"Pelayanan Publik","text":"Seorang warga mengurus dokumen tetapi syaratnya tidak lengkap. Warga tersebut datang dari jauh. Sikap Anda...","options":[{"id":"A","text":"Menolak berkas dan menyuruh pulang","score":1},{"id":"B","text":"Menjelaskan kekurangan dengan sabar dan memberikan solusi alternatif","score":5},{"id":"C","text":"Menerima berkas apa adanya","score":2},{"id":"D","text":"Menjawab seperlunya","score":3},{"id":"E","text":"Meminta rekan untuk menjelaskan","score":4}],"correct":"B","explanation":"Pelayanan prima berarti tidak hanya menolak, tetapi juga memberikan solusi dan informasi yang jelas agar warga tidak bolak-balik. Empati dan solusi adalah kunci.","xp_reward":10,"coin_reward":5},

  // ── PROFESIONALISME (+7) ──
  {"id":"TKP-077","category":"TKP","sub":"Profesionalisme","text":"Anda sedang memimpin rapat, tetapi ada peserta yang asyik bermain HP. Sikap profesional Anda...","options":[{"id":"A","text":"Mengabaikan","score":1},{"id":"B","text":"Menegur dengan sopan dan mengingatkan etika rapat","score":5},{"id":"C","text":"Memarahi di depan semua orang","score":2},{"id":"D","text":"Menyindir saat bicara","score":3},{"id":"E","text":"Menghentikan rapat","score":4}],"correct":"B","explanation":"Profesionalisme berarti menjaga etika dan ketertiban rapat tanpa merendahkan. Teguran sopan lebih efektif membangun budaya kerja yang profesional.","xp_reward":10,"coin_reward":5},
  
  // ── SOSIAL BUDAYA (+9) ──
  {"id":"TKP-078","category":"TKP","sub":"Sosial Budaya","text":"Rekan kerja Anda berbeda keyakinan dan meminta izin untuk melaksanakan ibadah di jam kerja. Sikap Anda...","options":[{"id":"A","text":"Melarang karena jam kerja","score":1},{"id":"B","text":"Mendukung dan memfasilitasi agar urusan kantor tetap berjalan","score":5},{"id":"C","text":"Membiarkan tanpa peduli","score":2},{"id":"D","text":"Mengusulkan jadwal ibadah di luar jam kerja","score":3},{"id":"E","text":"Mempersilakan tapi memasang raport","score":4}],"correct":"B","explanation":"Toleransi beragama adalah nilai dasar bangsa Indonesia. Mendukung rekan beribadah sambil memastikan pekerjaan tetap berjalan adalah sikap sosial budaya yang tepat.","xp_reward":10,"coin_reward":5},
  
  // ── JEJARING KERJA (+7) ──
  {"id":"TKP-079","category":"TKP","sub":"Jejaring Kerja","text":"Instansi Anda bekerja sama dengan pihak swasta. Anda diminta menjadi penghubung (liaison officer). Sikap Anda...","options":[{"id":"A","text":"Menolak karena tambahan kerja","score":1},{"id":"B","text":"Menerima dan membangun relasi profesional yang saling menguntungkan","score":5},{"id":"C","text":"Menerima tapi pasif","score":2},{"id":"D","text":"Mendelegasikan ke staf lain","score":3},{"id":"E","text":"Menerima dengan syarat insentif","score":4}],"correct":"B","explanation":"Jejaring kerja adalah kompetensi penting ASN. Menjadi liaison officer adalah kesempatan membangun relasi yang bermanfaat bagi instansi dan pengembangan karier.","xp_reward":10,"coin_reward":5},
  
  // ── TIK (+5) ──
  {"id":"TKP-080","category":"TKP","sub":"TIK","text":"Pemerintah mewajibkan penggunaan tanda tangan elektronik untuk dokumen dinas. Anda belum terbiasa. Sikap Anda...","options":[{"id":"A","text":"Menolak menggunakan","score":1},{"id":"B","text":"Mempelajari penggunaan tanda tangan elektronik melalui tutorial dan pelatihan","score":5},{"id":"C","text":"Meminta staf untuk mengurus","score":2},{"id":"D","text":"Menggunakan tanda tangan basah diam-diam","score":3},{"id":"E","text":"Menunggu pelatihan resmi","score":4}],"correct":"B","explanation":"Perkembangan TIK di pemerintahan tidak bisa dihindari. Sikap proaktif mempelajari teknologi baru adalah wujud profesionalisme dan adaptasi di era digital.","xp_reward":10,"coin_reward":5}
];

const fp = path.join(__dirname, "..", "src", "data", "questions", "tkp.json");
const d = JSON.parse(fs.readFileSync(fp, "utf-8"));
const b = d.length; d.push(...NEW);
fs.writeFileSync(fp, JSON.stringify(d, null, 2), "utf-8");
console.log("TKP:", b, "→", d.length, "+" + NEW.length);
const s = {}; d.forEach(q => s[q.sub] = (s[q.sub]||0)+1);
Object.entries(s).sort((a,e)=>a[0].localeCompare(e[0])).forEach(([k,v]) => console.log(" ", k+":", v));
