const fs = require("fs"), path = require("path");
const NEW = [
  {"id":"TKP-094","category":"TKP","sub":"Kerja Sama","text":"Rekan Anda selalu mengambil kredit atas pekerjaan tim. Sikap Anda...","options":[{"id":"A","text":"Bekerja sendiri-sendiri","score":2},{"id":"B","text":"Mengkomunikasikan secara terbuka dalam evaluasi tim tentang kontribusi masing-masing","score":5},{"id":"C","text":"Melakukan hal yang sama","score":1},{"id":"D","text":"Melaporkan ke atasan","score":4},{"id":"E","text":"Mengurangi kontribusi","score":3}],"correct":"B","explanation":"Kerja sama yang sehat membutuhkan transparansi. Komunikasi terbuka tentang kontribusi dalam forum evaluasi lebih baik daripada konfrontasi atau balas dendam.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-095","category":"TKP","sub":"Kerja Sama","text":"Tim Anda mendapat anggota baru yang belum berpengalaman. Sikap Anda...","options":[{"id":"A","text":"Membiarkannya belajar sendiri","score":1},{"id":"B","text":"Membimbing dan berbagi pengalaman agar cepat beradaptasi","score":5},{"id":"C","text":"Memberi tugas yang paling sulit agar belajar cepat","score":2},{"id":"D","text":"Menugaskan anggota lain untuk membimbing","score":4},{"id":"E","text":"Mengkritik jika melakukan kesalahan","score":3}],"correct":"B","explanation":"Kerja sama berarti saling menguatkan. Membimbing anggota baru adalah investasi untuk kinerja tim jangka panjang.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-096","category":"TKP","sub":"Kerja Sama","text":"Anggota tim Anda sedang terlibat konflik pribadi yang mempengaruhi kinerja. Sikap Anda...","options":[{"id":"A","text":"Tidak ikut campur","score":2},{"id":"B","text":"Memediasi dan mengingatkan tujuan bersama tim","score":5},{"id":"C","text":"Memihak salah satu","score":1},{"id":"D","text":"Melaporkan ke atasan","score":4},{"id":"E","text":"Membicarakan dengan anggota lain","score":3}],"correct":"B","explanation":"Konflik pribadi yang berdampak pada kerja harus diselesaikan. Mediasi internal lebih baik daripada melibatkan atasan untuk masalah yang masih bisa diselesaikan di tingkat tim.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-097","category":"TKP","sub":"Kerja Sama","text":"Tim Anda bekerja lintas divisi. Divisi lain sering terlambat memberikan data yang dibutuhkan. Sikap Anda...","options":[{"id":"A","text":"Mengeluh ke atasan mereka","score":2},{"id":"B","text":"Menjalin komunikasi yang lebih baik, membuat jadwal bersama, dan saling mengingatkan","score":5},{"id":"C","text":"Menunggu saja","score":1},{"id":"D","text":"Mengerjakan tanpa data dari mereka","score":3},{"id":"E","text":"Membuat prosedur tertulis","score":4}],"correct":"B","explanation":"Kerja sama lintas divisi membutuhkan koordinasi proaktif. Komunikasi dan jadwal bersama lebih efektif daripada komplain atau pasif.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-098","category":"TKP","sub":"Profesionalisme","text":"Anda mendapat tawaran pekerjaan sampingan yang menarik di luar jam kerja. Pekerjaan tidak terkait dengan instansi. Sikap profesional Anda...","options":[{"id":"A","text":"Menerima tanpa melapor","score":2},{"id":"B","text":"Memeriksa aturan kepegawaian tentang izin pekerjaan sampingan, jika perlu izin resmi","score":5},{"id":"C","text":"Menolak karena takut ketahuan","score":1},{"id":"D","text":"Menerima dengan sembunyi-sembunyi","score":3},{"id":"E","text":"Menanyakan rekan yang sudah melakukannya","score":4}],"correct":"B","explanation":"Profesionalisme termasuk mematuhi aturan kepegawaian. Beberapa instansi mengizinkan pekerjaan sampingan dengan syarat tertentu. Periksa aturan dan urus izin resmi jika diperlukan.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-099","category":"TKP","sub":"Sosial Budaya","text":"Dalam rapat, ada usulan dari rekan yang berbeda latar belakang etnis. Usulannya bagus tapi penyampaiannya kurang sistematis. Sikap Anda...","options":[{"id":"A","text":"Mengabaikan karena cara penyampaiannya kurang baik","score":1},{"id":"B","text":"Mendukung substansi usulannya dan membantu merapikan penyampaian","score":5},{"id":"C","text":"Mengkritik cara penyampaiannya","score":2},{"id":"D","text":"Diam saja","score":3},{"id":"E","text":"Meminta rekan tersebut berbicara lebih jelas","score":4}],"correct":"B","explanation":"Sosial budaya berarti menghargai perbedaan gaya komunikasi dan fokus pada substansi. Membantu rekan menyampaikan ide adalah wujud gotong royong.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-100","category":"TKP","sub":"Sosial Budaya","text":"Ada tradisi di kantor yang menurut Anda kurang efektif tapi sudah dilakukan bertahun-tahun. Sikap Anda...","options":[{"id":"A","text":"Mengkritik tradisi tersebut","score":2},{"id":"B","text":"Memahami latar belakang tradisi, lalu mengusulkan perbaikan secara bertahap dengan data","score":5},{"id":"C","text":"Mengabaikan dan tidak ikut","score":1},{"id":"D","text":"Ikut tanpa berpikir","score":3},{"id":"E","text":"Membicarakannya dengan rekan sesama generasi","score":4}],"correct":"B","explanation":"Perubahan budaya butuh pendekatan yang bijak. Memahami akar tradisi dan mengusulkan perbaikan bertahap dengan data lebih efektif daripada kritik langsung.","xp_reward":10,"coin_reward":5}
];

const fp = path.join(__dirname, "..", "src", "data", "questions", "tkp.json");
const d = JSON.parse(fs.readFileSync(fp, "utf-8"));
const b = d.length; d.push(...NEW);
fs.writeFileSync(fp, JSON.stringify(d, null, 2), "utf-8");
console.log("TKP:", b, "\u2192", d.length, "+" + NEW.length);
const s = {}; d.forEach(q => s[q.sub] = (s[q.sub]||0)+1);
Object.entries(s).sort((a,e)=>a[0].localeCompare(e[0])).forEach(([k,v]) => console.log(" ", k+":", v));
