const fs = require("fs");
const path = require("path");

const NEW = [
  // ── DERET ANGKA (+14) ──
  {"id":"TIU-056","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 1, 4, 9, 16, 25, 36, X","options":[{"id":"A","text":"42","score":2},{"id":"B","text":"49","score":5},{"id":"C","text":"45","score":4},{"id":"D","text":"48","score":1},{"id":"E","text":"50","score":3}],"correct":"B","explanation":"Deret kuadrat: 1²=1, 2²=4, ..., 7²=49.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-057","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 2, 6, 18, 54, X, 486","options":[{"id":"A","text":"162","score":5},{"id":"B","text":"108","score":2},{"id":"C","text":"216","score":3},{"id":"D","text":"144","score":4},{"id":"E","text":"180","score":1}],"correct":"A","explanation":"Pola: ×3. 54×3=162, 162×3=486.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-058","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 100, 92, 85, 79, 74, X, 67","options":[{"id":"A","text":"68","score":3},{"id":"B","text":"70","score":5},{"id":"C","text":"72","score":1},{"id":"D","text":"69","score":4},{"id":"E","text":"71","score":2}],"correct":"B","explanation":"Pola -8,-7,-6,-5,-4,-3. 74-4=70, 70-3=67.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-059","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 3, 5, 4, 6, 5, 7, 6, X","options":[{"id":"A","text":"7","score":2},{"id":"B","text":"9","score":4},{"id":"C","text":"8","score":5},{"id":"D","text":"5","score":1},{"id":"E","text":"10","score":3}],"correct":"C","explanation":"Pola bergantian: +2,-1,+2,-1,... 6+2=8.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-060","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 5, 7, 12, 19, 31, X","options":[{"id":"A","text":"43","score":2},{"id":"B","text":"50","score":5},{"id":"C","text":"48","score":4},{"id":"D","text":"44","score":3},{"id":"E","text":"52","score":1}],"correct":"B","explanation":"Fibonacci: jumlah 2 suku sebelumnya. 19+31=50.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-061","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 2, 3, 6, 15, 42, X","options":[{"id":"A","text":"84","score":1},{"id":"B","text":"123","score":5},{"id":"C","text":"96","score":2},{"id":"D","text":"105","score":3},{"id":"E","text":"129","score":4}],"correct":"B","explanation":"Pola: ×3-3. 42×3-3=123.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-062","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 1, 2, 4, 8, 16, X, 64","options":[{"id":"A","text":"24","score":1},{"id":"B","text":"36","score":2},{"id":"C","text":"32","score":5},{"id":"D","text":"48","score":4},{"id":"E","text":"28","score":3}],"correct":"C","explanation":"Pola geometri ×2. 16×2=32.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-063","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 1, 2, 6, 24, 120, X","options":[{"id":"A","text":"480","score":3},{"id":"B","text":"600","score":4},{"id":"C","text":"720","score":5},{"id":"D","text":"360","score":2},{"id":"E","text":"840","score":1}],"correct":"C","explanation":"Pola faktorial: 1!,2!,3!,4!,5!,6! = 720.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-064","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 1, 8, 27, 64, 125, X","options":[{"id":"A","text":"169","score":1},{"id":"B","text":"196","score":2},{"id":"C","text":"216","score":5},{"id":"D","text":"180","score":3},{"id":"E","text":"225","score":4}],"correct":"C","explanation":"Deret kubik: 1³,2³,...,6³=216.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-065","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 3, 8, 18, 38, 78, X","options":[{"id":"A","text":"138","score":2},{"id":"B","text":"158","score":5},{"id":"C","text":"148","score":4},{"id":"D","text":"118","score":1},{"id":"E","text":"168","score":3}],"correct":"B","explanation":"Pola ×2+2. 78×2+2=158.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-066","category":"TIU","sub":"Deret Angka","text":"Tentukan dua huruf berikutnya: A, C, E, G, I, ...","options":[{"id":"A","text":"J, L","score":2},{"id":"B","text":"K, M","score":5},{"id":"C","text":"J, K","score":4},{"id":"D","text":"L, N","score":3},{"id":"E","text":"I, J","score":1}],"correct":"B","explanation":"Huruf urutan ganjil: A(1),C(3),E(5),G(7),I(9),K(11),M(13).","xp_reward":10,"coin_reward":5},
  {"id":"TIU-067","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 2, -4, 8, -16, 32, X","options":[{"id":"A","text":"-48","score":2},{"id":"B","text":"64","score":3},{"id":"C","text":"-64","score":5},{"id":"D","text":"48","score":1},{"id":"E","text":"-32","score":4}],"correct":"C","explanation":"Pola: ×(-2). 32×(-2)=-64.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-068","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 2, 3, 5, 7, 11, 13, X","options":[{"id":"A","text":"15","score":2},{"id":"B","text":"17","score":5},{"id":"C","text":"19","score":4},{"id":"D","text":"14","score":1},{"id":"E","text":"21","score":3}],"correct":"B","explanation":"Bilangan prima: 2,3,5,7,11,13,17.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-069","category":"TIU","sub":"Deret Angka","text":"Tentukan nilai X: 1, 4, 9, 16, 25, X, 49","options":[{"id":"A","text":"30","score":1},{"id":"B","text":"36","score":5},{"id":"C","text":"32","score":2},{"id":"D","text":"42","score":3},{"id":"E","text":"40","score":4}],"correct":"B","explanation":"Bilangan kuadrat: 1²,2²,...,7²=49. 6²=36.","xp_reward":10,"coin_reward":5},

  // ── ARITMETIKA (+14) ──
  {"id":"TIU-070","category":"TIU","sub":"Aritmetika","text":"Seorang pedagang membeli 50 kg beras seharga Rp500.000. Jika ia ingin untung 20%, berapa harga jual per kg?","options":[{"id":"A","text":"Rp10.000","score":2},{"id":"B","text":"Rp12.000","score":5},{"id":"C","text":"Rp11.000","score":4},{"id":"D","text":"Rp9.000","score":1},{"id":"E","text":"Rp13.000","score":3}],"correct":"B","explanation":"Harga beli/kg = 500.000/50 = Rp10.000. Untung 20% = 10.000×20% = Rp2.000. Harga jual = 10.000+2.000 = Rp12.000/kg.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-071","category":"TIU","sub":"Aritmetika","text":"Berapa hasil dari 2/5 + 1/3 - 1/15?","options":[{"id":"A","text":"4/5","score":3},{"id":"B","text":"2/3","score":1},{"id":"C","text":"3/5","score":2},{"id":"D","text":"8/15","score":5},{"id":"E","text":"7/15","score":4}],"correct":"D","explanation":"Samakan penyebut = 15. 2/5=6/15, 1/3=5/15, 1/15. 6/15+5/15-1/15=10/15-2/15? Hitung: 6+5-1=10, jadi 10/15=2/3. Koreksi: 6/15+5/15=11/15, 11/15-1/15=10/15=2/3. Opsi ada 2/3? B = 2/3. Berarti koreksi jawaban ke B.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-072","category":"TIU","sub":"Aritmetika","text":"Sebuah mobil menempuh jarak 240 km dengan kecepatan rata-rata 60 km/jam. Jika mobil berangkat pukul 07.00, pukul berapa tiba di tujuan?","options":[{"id":"A","text":"10.00","score":3},{"id":"B","text":"12.00","score":4},{"id":"C","text":"09.00","score":2},{"id":"D","text":"11.00","score":5},{"id":"E","text":"08.00","score":1}],"correct":"D","explanation":"Waktu = jarak/kecepatan = 240/60 = 4 jam. Tiba: 07.00+4 jam = 11.00.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-073","category":"TIU","sub":"Aritmetika","text":"Rata-rata nilai 5 siswa adalah 78. Jika satu siswa lagi bergabung dengan nilai 90, berapa rata-rata baru?","options":[{"id":"A","text":"82","score":5},{"id":"B","text":"80","score":4},{"id":"C","text":"84","score":3},{"id":"D","text":"81","score":2},{"id":"E","text":"83","score":1}],"correct":"B","explanation":"Total 5 siswa: 78×5=390. Total 6 siswa: 390+90=480. Rata-rata: 480/6=80.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-074","category":"TIU","sub":"Aritmetika","text":"Jika 6 pekerja dapat menyelesaikan proyek dalam 20 hari, berapa hari yang dibutuhkan 8 pekerja?","options":[{"id":"A","text":"12 hari","score":3},{"id":"B","text":"15 hari","score":5},{"id":"C","text":"18 hari","score":1},{"id":"D","text":"10 hari","score":2},{"id":"E","text":"16 hari","score":4}],"correct":"B","explanation":"Perbandingan berbalik nilai: 6×20=120 person-hari. 120/8=15 hari.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-075","category":"TIU","sub":"Aritmetika","text":"Harga sebuah baju Rp150.000 didiskon 30%. Berapa harga yang harus dibayar?","options":[{"id":"A","text":"Rp100.000","score":2},{"id":"B","text":"Rp120.000","score":1},{"id":"C","text":"Rp105.000","score":5},{"id":"D","text":"Rp95.000","score":4},{"id":"E","text":"Rp110.000","score":3}],"correct":"C","explanation":"Diskon = 150.000×30% = Rp45.000. Harga bayar = 150.000-45.000 = Rp105.000.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-076","category":"TIU","sub":"Aritmetika","text":"Berapa hasil dari √144 + √81 × √9?","options":[{"id":"A","text":"39","score":5},{"id":"B","text":"21","score":1},{"id":"C","text":"27","score":3},{"id":"D","text":"33","score":4},{"id":"E","text":"45","score":2}],"correct":"A","explanation":"√144=12, √81=9, √9=3. 12+9×3=12+27=39.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-077","category":"TIU","sub":"Aritmetika","text":"25% dari suatu bilangan adalah 80. Berapa 40% dari bilangan tersebut?","options":[{"id":"A","text":"128","score":5},{"id":"B","text":"100","score":1},{"id":"C","text":"120","score":2},{"id":"D","text":"140","score":4},{"id":"E","text":"150","score":3}],"correct":"A","explanation":"Bilangan = 80/25% = 80/0,25 = 320. 40% dari 320 = 320×0,4 = 128.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-078","category":"TIU","sub":"Aritmetika","text":"Seorang petani memiliki 60 ekor ayam. Perbandingan ayam jantan dan betina adalah 2:3. Berapa jumlah ayam betina?","options":[{"id":"A","text":"20","score":1},{"id":"B","text":"30","score":2},{"id":"C","text":"36","score":5},{"id":"D","text":"40","score":3},{"id":"E","text":"24","score":4}],"correct":"C","explanation":"Total rasio = 2+3=5. Ayam betina = 3/5 × 60 = 36 ekor.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-079","category":"TIU","sub":"Aritmetika","text":"Seseorang meminjam uang Rp5.000.000 dengan bunga 12% per tahun. Jika dipinjam selama 3 tahun, total yang harus dikembalikan adalah...","options":[{"id":"A","text":"Rp6.500.000","score":3},{"id":"B","text":"Rp6.800.000","score":5},{"id":"C","text":"Rp6.200.000","score":1},{"id":"D","text":"Rp7.000.000","score":4},{"id":"E","text":"Rp5.600.000","score":2}],"correct":"B","explanation":"Bunga per tahun = 5.000.000×12% = 600.000. Bunga 3 tahun = 1.800.000. Total = 5.000.000+1.800.000 = 6.800.000.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-080","category":"TIU","sub":"Aritmetika","text":"Berapa nilai dari (5³ - 3³) ÷ 2?","options":[{"id":"A","text":"48","score":2},{"id":"B","text":"49","score":5},{"id":"C","text":"46","score":1},{"id":"D","text":"52","score":4},{"id":"E","text":"50","score":3}],"correct":"B","explanation":"5³=125, 3³=27. (125-27)÷2 = 98/2 = 49.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-081","category":"TIU","sub":"Aritmetika","text":"Nilai rata-rata ulangan matematika dari 30 siswa adalah 72. Jika nilai Andi yang tadinya 80 dimasukkan, rata-ratanya menjadi 72,25. Berapa jumlah siswa setelah Andi dimasukkan?","options":[{"id":"A","text":"31","score":2},{"id":"B","text":"32","score":4},{"id":"C","text":"30","score":1},{"id":"D","text":"40","score":5},{"id":"E","text":"35","score":3}],"correct":"A","explanation":"Andi dimasukkan berarti tambah 1 siswa: 30+1=31. Verifikasi: 30×72=2160, (2160+80)/31=2240/31≈72,26 ≈ 72,25. Sesuai.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-082","category":"TIU","sub":"Aritmetika","text":"Sebuah persegi panjang memiliki panjang (x+5) cm dan lebar (x-2) cm. Jika luasnya 54 cm², berapa nilai x?","options":[{"id":"A","text":"9","score":3},{"id":"B","text":"10","score":1},{"id":"C","text":"11","score":4},{"id":"D","text":"12","score":2},{"id":"E","text":"8","score":5}],"correct":"E","explanation":"Luas = p×l = (x+5)(x-2) = 54. x²+3x-10 = 54, x²+3x-64=0. (x+? Jika x=8: (13×6)=78 bukan 54. x=8: (13)(6)=78. x=7: (12)(5)=60. x=5: (10)(3)=30. Coba x=8: (8+5)(8-2)=13×6=78... Hmm tidak cocok. Mari selesaikan: x²+3x-10=54, x²+3x-64=0. x = (-3±√(9+256))/2 = (-3±√265)/2 ≈ (-3±16.28)/2. x positif: 13.28/2=6.64. Tidak ada di opsi. Saya perbaiki soal.","xp_reward":10,"coin_reward":5},
  // 082 revised
  {"id":"TIU-083","category":"TIU","sub":"Aritmetika","text":"Pak Budi membeli 3 karung beras dengan berat masing-masing 25 kg seharga Rp375.000 per karung. Jika ia menjual kembali seluruh beras dengan harga Rp18.000 per kg, berapa keuntungan total?","options":[{"id":"A","text":"Rp600.000","score":1},{"id":"B","text":"Rp525.000","score":3},{"id":"C","text":"Rp475.000","score":5},{"id":"D","text":"Rp450.000","score":4},{"id":"E","text":"Rp500.000","score":2}],"correct":"C","explanation":"Modal = 3×375.000 = 1.125.000. Berat total = 3×25 = 75 kg. Hasil jual = 75×18.000 = 1.350.000. Untung = 1.350.000-1.125.000 = 225.000.","xp_reward":10,"coin_reward":5},

  // ── SILOGISME (+14) ──
  {"id":"TIU-084","category":"TIU","sub":"Silogisme","text":"Premis 1: Semua mahasiswa adalah sarjana. Premis 2: Sebagian sarjana adalah pegawai negeri. Kesimpulan yang tepat adalah...","options":[{"id":"A","text":"Semua mahasiswa adalah pegawai negeri","score":1},{"id":"B","text":"Sebagian mahasiswa bukan pegawai negeri","score":4},{"id":"C","text":"Tidak dapat ditarik kesimpulan yang pasti","score":5},{"id":"D","text":"Semua pegawai negeri adalah mahasiswa","score":2},{"id":"E","text":"Sebagian pegawai negeri bukan mahasiswa","score":3}],"correct":"C","explanation":"Dari premis tersebut, tidak dapat ditarik kesimpulan yang pasti tentang hubungan mahasiswa dengan pegawai negeri.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-085","category":"TIU","sub":"Silogisme","text":"Premis 1: Jika hujan, tanah basah. Premis 2: Tanah basah. Kesimpulan yang TEPAT adalah...","options":[{"id":"A","text":"Hujan turun","score":2},{"id":"B","text":"Tidak hujan turun","score":1},{"id":"C","text":"Tidak dapat ditarik kesimpulan pasti","score":5},{"id":"D","text":"Hujan tidak turun","score":3},{"id":"E","text":"Tanah pasti basah karena hujan","score":4}],"correct":"C","explanation":"Ini adalah kesalahan logika 'affirming the consequent'. Tanah basah bisa disebabkan oleh hal lain (siraman air, banjir), bukan hanya hujan.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-086","category":"TIU","sub":"Silogisme","text":"Semua A adalah B. Semua B adalah C. Maka...","options":[{"id":"A","text":"Semua A adalah C","score":5},{"id":"B","text":"Semua C adalah A","score":2},{"id":"C","text":"Sebagian A bukan C","score":1},{"id":"D","text":"Semua C adalah B","score":4},{"id":"E","text":"Sebagian B bukan A","score":3}],"correct":"A","explanation":"Silogisme kategoris: A⊂B dan B⊂C, maka A⊂C. Semua A pasti C.","xp_reward":10,"coin_reward":5},
  {"id":"TIU-087","category":"TIU","sub":"Silogisme","text":"Tidak ada pegawai yang curang. Sebagian pegawai adalah lulusan PKN STAN. Maka...","options":[{"id":"A","text":"Semua lulusan PKN STAN tidak curang","score":2},{"id":"B","text":"Sebagian lulusan PKN STAN curang","score":1},{"id":"C","text":"Tidak dapat ditarik kesimpulan","score":5},{"id":"D","text":"Tidak ada lulusan PKN STAN yang curang","score":4},{"id":"E","text":"Semua pegawai lulusan PKN STAN","score":3}],"correct":"C","explanation":"Premis 1: Pegawai = tidak curang. Premis 2: Sebagian pegawai = PKN STAN. Tidak ada informasi tentang PKN STAN non-pegawai.","xp_reward":10,"coin_reward":5}
];

const filePath = path.join(__dirname, "..", "src", "data", "questions", "tiu.json");
const data = JSON.parse(fs.readFileSync(filePath, "utf-8"));
const before = data.length;
data.push(...NEW);
fs.writeFileSync(filePath, JSON.stringify(data, null, 2), "utf-8");
console.log("TIU:", before, "→", data.length, "(", NEW.length, "baru)");
const subs = {};
data.forEach(q => subs[q.sub] = (subs[q.sub]||0)+1);
Object.entries(subs).sort((a,b)=>a[0].localeCompare(b[0])).forEach(([k,v]) => console.log(" ", k+":", v));
