const fs = require("fs"), path = require("path");
const NEW = [
  // ── INTEGRITAS (+14) ──
  {"id":"TKP-056","category":"TKP","sub":"Integritas","text":"Anda sedang mengikuti bimtek di luar kota. Teman sekamar Anda menawarkan untuk memalsukan tanda tangan absensi agar Anda bisa jalan-jalan. Sikap Anda...","options":[{"id":"A","text":"Menerima tawaran karena sudah capek bimtek terus","score":1},{"id":"B","text":"Menolak dengan halus dan menjelaskan pentingnya integritas","score":5},{"id":"C","text":"Memalsukan tapi hanya sekali saja","score":2},{"id":"D","text":"Menyuruh teman untuk ikut jalan-jalan","score":3},{"id":"E","text":"Melaporkan teman ke panitia","score":4}],"correct":"B","explanation":"Integritas berarti konsisten antara nilai dan tindakan meskipun dalam situasi yang menggoda. Menolak dengan halus sambil mengedukasi teman adalah sikap terbaik.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-057","category":"TKP","sub":"Integritas","text":"Anda menemukan dompet berisi uang jutaan rupiah di toilet kantor. Tidak ada saksi. Anda sedang butuh uang untuk biaya pengobatan orang tua. Tindakan Anda...","options":[{"id":"A","text":"Mengambil uangnya karena tidak ada yang tahu","score":1},{"id":"B","text":"Menitipkan dompet ke security dan mencari tahu pemiliknya melalui KTP","score":5},{"id":"C","text":"Mengambil sebagian uangnya, sisanya dikembalikan","score":2},{"id":"D","text":"Menunggu pemilik datang mencari","score":3},{"id":"E","text":"Menitipkan ke rekan kerja terdekat","score":4}],"correct":"B","explanation":"Integritas diuji saat tidak ada yang mengawasi. Menitipkan ke security dan mengupayakan pengembalian penuh ke pemilik adalah tindakan yang tepat meskipun Anda sedang butuh.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-058","category":"TKP","sub":"Adaptasi","text":"Instansi Anda berganti sistem aplikasi kerja secara total. Anda sudah nyaman dengan sistem lama. Sikap Anda...","options":[{"id":"A","text":"Menolak menggunakan sistem baru","score":1},{"id":"B","text":"Mempelajari sistem baru dengan antusias dan membantu rekan yang kesulitan","score":5},{"id":"C","text":"Menggunakan sistem lama selama masih bisa","score":2},{"id":"D","text":"Menunggu instruksi detail dari atasan","score":3},{"id":"E","text":"Mengeluh ke sesama rekan kerja","score":4}],"correct":"B","explanation":"Kemampuan adaptasi ditunjukkan dengan sikap proaktif dalam mempelajari perubahan dan membantu orang lain, bukan menolak atau pasif menunggu.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-059","category":"TKP","sub":"Adaptasi","text":"Anda dipindahkan ke unit kerja baru dengan budaya kerja yang sangat berbeda. Rekan baru Anda cenderung tertutup. Sikap Anda...","options":[{"id":"A","text":"Menarik diri dan hanya fokus kerja","score":1},{"id":"B","text":"Mendekati rekan secara perlahan, mengamati budaya kerja, dan menyesuaikan diri","score":5},{"id":"C","text":"Mengajak rekan untuk mengikuti cara kerja lama Anda","score":2},{"id":"D","text":"Mengadu ke atasan tentang budaya kerja yang buruk","score":3},{"id":"E","text":"Pindah unit lagi","score":4}],"correct":"B","explanation":"Adaptasi di lingkungan baru membutuhkan kesabaran, observasi, dan fleksibilitas. Mendekati secara perlahan lebih efektif daripada memaksakan perubahan.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-060","category":"TKP","sub":"Adaptasi","text":"Atasan memberi tugas yang belum pernah Anda kerjakan sebelumnya. Deadline mepet dan tidak ada pelatihan. Sikap Anda...","options":[{"id":"A","text":"Menolak karena tidak mampu","score":1},{"id":"B","text":"Menerima, mempelajari mandiri, dan bertanya ke rekan yang lebih berpengalaman","score":5},{"id":"C","text":"Mengerjakan setengah hati","score":2},{"id":"D","text":"Meminta perpanjangan waktu tanpa berusaha","score":3},{"id":"E","text":"Mendelegasikan ke bawahan","score":4}],"correct":"B","explanation":"Kemampuan adaptasi dan inisiatif ditunjukkan dengan menerima tantangan baru, belajar mandiri, dan memanfaatkan sumber daya yang ada (rekan berpengalaman).","xp_reward":10,"coin_reward":5},
  {"id":"TKP-061","category":"TKP","sub":"Kerja Sama","text":"Anggota tim Anda ada yang tidak berkontribusi sama sekali dalam proyek kelompok. Sikap Anda...","options":[{"id":"A","text":"Membiarkan dan mengerjakan sendiri","score":2},{"id":"B","text":"Mendekati secara pribadi, menanyakan kendala, dan menawarkan bantuan","score":5},{"id":"C","text":"Melaporkan ke atasan","score":3},{"id":"D","text":"Mengeluarkan dari tim","score":1},{"id":"E","text":"Membicarakan di grup tanpa menegur langsung","score":4}],"correct":"B","explanation":"Kerja sama tim yang baik membutuhkan komunikasi interpersonal. Mendekati secara pribadi untuk memahami kendala lebih efektif daripada konfrontasi publik atau pelaporan.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-062","category":"TKP","sub":"Kerja Sama","text":"Tim Anda memiliki pandangan berbeda dalam menyelesaikan masalah. Anda yakin pendapat Anda yang paling tepat. Sikap Anda...","options":[{"id":"A","text":"Memaksakan pendapat karena paling yakin","score":2},{"id":"B","text":"Mendengarkan semua pendapat, mencari titik temu, dan mengambil keputusan bersama","score":5},{"id":"C","text":"Diam dan mengikuti apapun keputusan mayoritas","score":1},{"id":"D","text":"Melakukan voting","score":3},{"id":"E","text":"Membawa ke atasan untuk diputuskan","score":4}],"correct":"B","explanation":"Kerja sama yang efektif tidak berarti memaksakan pendapat sendiri, melainkan mendengarkan, berdiskusi, dan mencapai konsensus. Kolaborasi lebih bernilai dari kemenangan argumen.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-063","category":"TKP","sub":"Pelayanan Publik","text":"Seorang warga lanjut usia datang ke kantor Anda untuk mengurus dokumen kependudukan. Beliau terlihat bingung dan tidak paham prosedur. Saat itu sedang ramai pengunjung. Sikap Anda...","options":[{"id":"A","text":"Menyuruhnya menunggu karena ada antrean","score":2},{"id":"B","text":"Membimbingnya dengan sabar dan memastikan dokumen lengkap sebelum antre","score":5},{"id":"C","text":"Memberi nomor antrean dan menyuruhnya ikut antre","score":1},{"id":"D","text":"Menjelaskan prosedur secara cepat","score":3},{"id":"E","text":"Meminta petugas lain yang lebih muda untuk membantunya","score":4}],"correct":"B","explanation":"Orientasi pelayanan berarti memberikan perhatian lebih kepada yang membutuhkan, termasuk warga lansia. Membimbing dengan sabar adalah bentuk pelayanan prima.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-064","category":"TKP","sub":"Profesionalisme","text":"Rekan kerja Anda membocorkan data rahasia perusahaan kepada pihak luar. Sikap profesional Anda...","options":[{"id":"A","text":"Ikut membocorkan karena sudah bocor","score":1},{"id":"B","text":"Menegur rekan dan melaporkan ke atasan melalui prosedur yang benar","score":5},{"id":"C","text":"Diam saja karena takut dianggap bermusuhan","score":2},{"id":"D","text":"Membicarakannya dengan rekan lain","score":3},{"id":"E","text":"Memberi peringatan lisan tanpa melapor","score":4}],"correct":"B","explanation":"Profesionalisme mencakup menjaga kerahasiaan dan menegakkan aturan. Menegur rekan lalu melapor melalui prosedur resmi adalah tindakan profesional.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-065","category":"TKP","sub":"Profesionalisme","text":"Anda memiliki janji pribadi di jam istirahat. Tiba-tiba ada pengaduan masyarakat yang butuh penanganan segera. Sikap profesional Anda...","options":[{"id":"A","text":"Menunda pengaduan karena jam istirahat","score":1},{"id":"B","text":"Menangani pengaduan terlebih dahulu, baru istirahat setelah selesai","score":5},{"id":"C","text":"Meminta rekan untuk menangani","score":3},{"id":"D","text":"Menangani setengahnya dan melanjutkan istirahat","score":2},{"id":"E","text":"Menjawab telepon sambil istirahat","score":4}],"correct":"B","explanation":"Profesionalisme berarti mengutamakan pelayanan publik di atas kepentingan pribadi. Istirahat bisa ditunda, tetapi kepentingan masyarakat adalah prioritas utama.","xp_reward":10,"coin_reward":5},
  {"id":"TKP-066","category":"TKP","sub":"Sosial Budaya","text":"Dalam tim kerja Anda ada anggota dari berbagai suku dan agama. Saat diskusi, ada yang membuat lelucon bernuansa SARA. Sikap Anda...","options":[{"id":"A","text":"Tertawa agar tidak dianggap tidak bisa bercanda","score":2},{"id":"B","text":"Menegur dengan halus dan mengingatkan pentingnya toleransi","score":5},{"id":"C","text":"Diam saja","score":1},{"id":"D","text":"Ikut bercanda agar suasana cair","score":3},{"id":"E","text":"Melaporkan ke HRD","score":4}],"correct":"B","explanation":"Dalam keberagaman, menjaga toleransi adalah kunci. Menegur dengan halus dan mengingatkan nilai Bhinneka Tunggal Ika adalah tindakan sosial budaya yang tepat.","xp_reward":10,"coin_reward":5}
];

const fp = path.join(__dirname, "..", "src", "data", "questions", "tkp.json");
const d = JSON.parse(fs.readFileSync(fp, "utf-8"));
const b = d.length; d.push(...NEW);
fs.writeFileSync(fp, JSON.stringify(d, null, 2), "utf-8");
console.log("TKP:", b, "→", d.length, "+" + NEW.length);
const s = {}; d.forEach(q => s[q.sub] = (s[q.sub]||0)+1);
Object.entries(s).sort((a,e)=>a[0].localeCompare(e[0])).forEach(([k,v]) => console.log(" ", k+":", v));
